accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^signup/$', views.signup, name='signup'),
]

blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<pk>\d+)/$', views.shop_detail, name='shop_detail'),
    url(r'^(?P<shop_pk>\d+)/review/new/$', views.review_new, name='review_new'),
    url(r'^(?P<shop_pk>\d+)/review/(?P<pk>\d+)/edit/$', views.review_edit, name='review_edit'),
    url(r'^(?P<pk>\d+)/category_detail/$', views.shop_list, name='category_detail'),
]

finalexam_younggi/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^$', lambda request: redirect('/blog/')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.conf import settings
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

class Category(models.Model):
    category = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.category

class Shop(models.Model):
    category = models.ForeignKey(Category)
    name = models.CharField(max_length=100)
    phonenumber = PhoneNumberField()
    address = models.TextField()
    content = models.TextField()
    photo1 = models.ImageField()
    photo2 = models.ImageField(blank=True)
    photo3 = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Review(models.Model):
    shop = models.ForeignKey(Shop)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    message = models.TextField()
    photoshot = models.ImageField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

blog/forms.py
from django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['message', 'photoshot']

accounts/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup_form.html', {
        'form': form,
    })

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Shop, Review
from .forms import ReviewForm
from django.contrib.auth.decorators import login_required

def index(request):
    category_list = Category.objects.all()
    return render(request, 'blog/index.html', {
        'category_list':category_list,
    })

def shop_list(request, pk):
    shop_list = Shop.objects.all()
    return render(request, 'blog/category_detail.html', {
        'shop_list': shop_list,
    })

def shop_detail(request, pk):
    shop = get_object_or_404(Shop, pk=pk)
    return render(request, 'blog/shop_detail.html', {
        'shop': shop,
    })

@login_required
def review_new(request, shop_pk):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = get_object_or_404(Shop, pk=shop_pk)
            review.user = request.user
            review.save()
            return redirect('blog:shop_detail', shop_pk)
    else:
        form = ReviewForm()
    return render(request, 'blog/review_form.html', {
        'form': form,
    })

@login_required
def review_edit(request, shop_pk, pk):
    review = get_object_or_404(Review, pk=pk)

    if request.method == 'POST':
        form = ReviewForm(request.POST, instance=review)
        if form.is_valid():
            review = form.save(commit=False)
            review.shop = get_object_or_404(Shop, pk=shop_pk)
            review.user = request.user
            review.save()
            return redirect('blog:shop_detail', shop_pk)
    else:
        form = ReviewForm(instance=review)
    return render(request, 'blog/review_form.html', {
        'form': form,
    })

accounts/templates/accounts/signup_form.html
<form action="" method="post" >
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/base.html
<!doctype html>
<html>
<head>
<meta charset="utf8" />
<title>Blog</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body {
    padding-top: 60px;
    padding-bottom: 30px;
}
</style>
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a href="{% url 'logout' %}?next={{ request.path }}">로그아웃</a></li>
            {% else %}
              <li><a href="{% url 'login' %}?next={{ request.path }}">로그인</a></li>
              <li><a href="{% url 'signup' %}">회원가입</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

blog/templates/blog/category_detail.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>{{ category.category }}</h1>
<ul>
    {% for shop in shop_list %}
        <li>
        <a href="{% url 'blog:shop_detail' shop.pk %}" >{{ shop.name }}</a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% block content %}
<ul>
    {% for category in category_list %}
    <ul>
        {{ category.category }}
            {% for shop in category.shop_set.all %}
            <li>
                {{ shop.name }}
                {{ shop.created_at }}

            </li>
            {% endfor %}
    </ul>
    {% endfor %}
</ul>
{% endblock %}

blog/templates/blog/review_form.html
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/shop_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>{{ shop.name }}</h1>

    {{ shop.created_at }}
    {{ shop.updated_at }}
    <hr/>

    <img src="{{ shop.photo1.url }}" width="50%", height="50%" />

    {{ shop.content|linebreaks }}

    <h3>댓글</h3>
    <a href="{% url 'blog:review_new' shop.pk %}" class="btn btn-primary btn-block">리뷰 쓰기</a>
    <ul>
    {% for review in shop.review_set.all %}
    <li>
        {{ review.message }}
        by {{ review.user }}
        {{ review.created_at }}

        <a href="{% url 'blog:review_edit' shop.pk review.pk %}">수정</a>
    </li>
    {% endfor %}
    </ul>
    <hr/>
    <a href="{% url 'blog:index' %}">글 목록</a>
 {% endblock %}